name: Prepare
description: Prepares the repo for a CI job

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: actions/checkout@v3
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
    - name: Install deps
      shell: bash
      run: bun install
